version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: collabbeats
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./collabserver
    env_file:
      - ./collabserver/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: collabbeats
      NODE_ENV: production
      CLIENT_ORIGIN: http://localhost
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./collabclient
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: 